/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/beetle.glb --types 
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import * as THREE from "three"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial013: THREE.Mesh
    defaultMaterial014: THREE.Mesh
    defaultMaterial015: THREE.Mesh
    defaultMaterial016: THREE.Mesh
    defaultMaterial017: THREE.Mesh
    defaultMaterial018: THREE.Mesh
    defaultMaterial009: THREE.Mesh
    defaultMaterial010: THREE.Mesh
    defaultMaterial011: THREE.Mesh
    defaultMaterial012: THREE.Mesh
    defaultMaterial005: THREE.Mesh
    defaultMaterial006: THREE.Mesh
    defaultMaterial007: THREE.Mesh
    defaultMaterial008: THREE.Mesh
    defaultMaterial001: THREE.Mesh
    defaultMaterial002: THREE.Mesh
    defaultMaterial003: THREE.Mesh
    defaultMaterial004: THREE.Mesh
    defaultMaterial: THREE.Mesh
  }
  materials: {
    vw_beetle_1969_mo_1003: THREE.MeshStandardMaterial
    vw_beetle_1969_mo_1001: THREE.MeshStandardMaterial
    vw_beetle_1969_mo_1004: THREE.MeshStandardMaterial
    vw_beetle_1969_mo_1002: THREE.MeshStandardMaterial
    vw_beetle_1969_mo_1005: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>

export function Beetle(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/beetle.glb") as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.6}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[6.131, 24.477, 45.097]}
            rotation={[-1.482, 0.174, -0.015]}
            scale={[1, 1.003, 1]}
          >
            <mesh
              geometry={nodes.defaultMaterial013.geometry}
              material={materials.vw_beetle_1969_mo_1003}
            />
            <mesh
              geometry={nodes.defaultMaterial014.geometry}
              material={materials.vw_beetle_1969_mo_1001}
            />
            <mesh
              geometry={nodes.defaultMaterial015.geometry}
              material={materials.vw_beetle_1969_mo_1004}
            />
            <mesh
              geometry={nodes.defaultMaterial016.geometry}
              material={materials.vw_beetle_1969_mo_1002}
            />
            <mesh
              geometry={nodes.defaultMaterial017.geometry}
              material={materials.vw_beetle_1969_mo_1005}
            />
            <mesh
              geometry={nodes.defaultMaterial018.geometry}
              material={materials.vw_beetle_1969_mo_1005}
            />
          </group>
          <group
            position={[5.138, 41.097, 45.618]}
            rotation={[-1.482, 0.174, -0.015]}
            scale={[1, 1.003, 1]}
          >
            <mesh
              geometry={nodes.defaultMaterial009.geometry}
              material={materials.vw_beetle_1969_mo_1001}
            />
            <mesh
              geometry={nodes.defaultMaterial010.geometry}
              material={materials.vw_beetle_1969_mo_1004}
            />
            <mesh
              geometry={nodes.defaultMaterial011.geometry}
              material={materials.vw_beetle_1969_mo_1003}
            />
            <mesh
              geometry={nodes.defaultMaterial012.geometry}
              material={materials.vw_beetle_1969_mo_1002}
            />
          </group>
          <group
            position={[6.131, 24.477, 45.097]}
            rotation={[-1.482, 0.174, -0.015]}
            scale={[1, 1.003, 1]}
          >
            <mesh
              geometry={nodes.defaultMaterial005.geometry}
              material={materials.vw_beetle_1969_mo_1005}
            />
            <mesh
              geometry={nodes.defaultMaterial006.geometry}
              material={materials.vw_beetle_1969_mo_1003}
            />
            <mesh
              geometry={nodes.defaultMaterial007.geometry}
              material={materials.vw_beetle_1969_mo_1001}
            />
            <mesh
              geometry={nodes.defaultMaterial008.geometry}
              material={materials.vw_beetle_1969_mo_1004}
            />
          </group>
          <group
            position={[6.131, 24.477, 45.097]}
            rotation={[-1.482, 0.174, -0.015]}
            scale={[1, 1.003, 1]}
          >
            <mesh
              geometry={nodes.defaultMaterial001.geometry}
              material={materials.vw_beetle_1969_mo_1005}
            />
            <mesh
              geometry={nodes.defaultMaterial002.geometry}
              material={materials.vw_beetle_1969_mo_1003}
            />
            <mesh
              geometry={nodes.defaultMaterial003.geometry}
              material={materials.vw_beetle_1969_mo_1001}
            />
            <mesh
              geometry={nodes.defaultMaterial004.geometry}
              material={materials.vw_beetle_1969_mo_1004}
            />
          </group>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.vw_beetle_1969_mo_1001}
            position={[5.138, 41.097, 45.618]}
            rotation={[-1.482, 0.174, -0.015]}
            scale={[1, 1.003, 1]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/beetle.glb")
